server:
  port: 1001
  servlet:
    context-path: /user

spring:
  application:
    name: oauth-user


eureka:
  client:
    service-url:
      #单机
      defaultZone: http://localhost:7001/eureka

security:
  oauth2:
    # OAuth2 Client 配置，对应 OAuth2ClientProperties 类
    client:
      client-id: api
      client-secret: api-secret
    # OAuth2 Resource 配置，对应 ResourceServerProperties 类
    resource:
      # 获得 Token 信息的 URL oauth/check_token 固定写法
      token-info-uri: http://127.0.0.1:9999/oauth-service/oauth/check_token
    # 访问令牌获取 URL，自定义的 oauth/token 固定写法  oauth-service 认证服务的前缀 没有可不写
    access-token-uri: http://127.0.0.1:9999/oauth-servce/oauth/token