server:
  port: 9999
  servlet:
    context-path: /oauth-service
spring:
  application:
    name: oauth-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.29.120.60:3306/oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
    main:
      allow-bean-definition-overriding: true
  redis:
    host: 119.29.120.60
    password: 123456
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
auth:
  ttl: 3600  #token存储到cookie的过期时间
  clientId: changgou
  clientSecret: changgou
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/changgou.jks
    secret: changgou  #密钥
    alias: changgou #证书别名
    password: changgou #证书密码


eureka:
#  instance:
#    prefer-ip-address: true
  client:
    service-url:
      #单机
      defaultZone: http://localhost:7001/eureka

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false
security:
  oauth2:
    client:
      client-id: lkz
      client-secret: lkz
      access-token-uri: http://localhost:9999/oauth-service/oauth/token
    resource:
      token-info-uri: http://localhost:9999/oauth-service/oauth/check_token
      user-info-uri: http://localhost:9999/oauth-service/getInfo