
server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 默认为false，设为true开启通过微服务创建路由的功能，即可以通过微服务名访问服务
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
        #enabled: true #是否开启网关
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8081          #匹配后提供服务的路由地址
          #uri: lb://cloud-payment-service #匹配后提供服务的路由地址  根据euerke服务名匹配路由
          predicates:
            - Path=/provider/**   #CloudPaymentService  服务的名字 请求前加这个

        - id: order_routh
          uri: http://localhost:8000
          #uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/order/**        # 断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


