spring:
  application:
    name: demoNacos
  cloud:
    nacos:
      #服务注册与发现
      discovery:
        namespace: 936cf895-8115-421d-8377-ab6339becd09
        service: ${spring.application.name}
        server-addr: 119.29.120.60:8848

server:
  port: 18080


#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://demo9001-provider