server:
  port: 9001
spring:
  application:
    name: demo9001-provider
  cloud:
    nacos:
      discovery:
        server-addr: http://119.29.120.60:8848
        service: ${spring.application.name}
        namespace: 936cf895-8115-421d-8377-ab6339becd09
        #cluster-name: beijing
        #metadata.version: v1 负载均衡 版本号调用
      # Sentinel 配置项，对应 SentinelProperties 配置属性类
    sentinel:
      enabled: true # 是否开启。默认为 true 开启
      eager: true # 是否饥饿加载。默认为 false 关闭
      transport:
        #clientIp: 119.29.120.60 # #地址被指定为CentOS的地址
        #dashboard: 119.29.120.60:81
        dashboard: localhost:81
        port: 8719

#springboot 提供监控功能
management:
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always